nav:
  - Home: index.md
  - changelog.md
  - Documentation:
    - docs/tasks.md
    - docs/project.md
  - Synopsis:
    - synopsis/index.md
    - synopsis/run.md
    - kraken query:
      - synopsis/query/index.md
      - synopsis/query/ls.md
      - synopsis/query/describe.md
      - synopsis/query/env.md
      - synopsis/query/visualize.md
